apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-hotel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-hotel
  template:
    metadata:
      labels:
        app: book-hotel
    spec:
      containers:
        - name: book-hotel
          image: gcr.io/windy-nation-464015-s2/book-hotel-service
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: book-hotel-env
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: book-hotel-env
  labels:
    app: book-hotel
---
apiVersion: v1
kind: Service
metadata:
  name: book-hotel-service
spec:
  selector:
    app: book-hotel
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
