apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-notification
  template:
    metadata:
      labels:
        app: hotel-notification
    spec:
      containers:
        - name: hotel-notification
          image: gcr.io/windy-nation-464015-s2/hotel-notification-service
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: hotel-notification-env
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hotel-notification-env
  labels:
    app: hotel-notification
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-notification-service
spec:
  selector:
    app: hotel-notification
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
