apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-ai-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-ai-agent
  template:
    metadata:
      labels:
        app: hotel-ai-agent
    spec:
      containers:
        - name: hotel-ai-agent
          image: gcr.io/windy-nation-464015-s2/hotel-ai-agent-service
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: hotel-ai-agent-env
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hotel-ai-agent-env
  labels:
    app: hotel-ai-agent
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-ai-agent-service
spec:
  selector:
    app: hotel-ai-agent
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
