apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-admin
  template:
    metadata:
      labels:
        app: hotel-admin
    spec:
      containers:
        - name: hotel-admin
          image: gcr.io/windy-nation-464015-s2/hotel-admin-service
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: hotel-admin-env
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hotel-admin-env
  labels:
    app: hotel-admin
data:
  REDIS_HOST: redis
  REDIS_PORT: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-admin-service
spec:
  selector:
    app: hotel-admin
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
