services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  api_gateway:
    build:
      context: ./api_gateway_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - book_hotel_service
      - hotel_admin_service
      - hotel_ai_agent_service
      - hotel_comments_service
      - hotel_search_service
      - hotel_notification_service
    env_file:
      - ./api_gateway_service/.env
      
  book_hotel_service:
    build:
      context: ./book_hotel_service
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - ./book_hotel_service/.env

  hotel_admin_service:
    build:
      context: ./hotel_admin_service
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    depends_on:
      - redis
    env_file:
      - ./hotel_admin_service/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  hotel_ai_agent_service:
    build:
      context: ./hotel_ai_agent_service
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    env_file:
      - ./hotel_ai_agent_service/.env

  hotel_comments_service:
    build:
      context: ./hotel_comments_service
      dockerfile: Dockerfile
    ports:
      - "8004:8000"

  hotel_search_service:
    build:
      context: ./hotel_search_service
      dockerfile: Dockerfile
    ports:
      - "8005:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  hotel_notification_service:
    build:
      context: ./hotel_notification_service
      dockerfile: Dockerfile
    ports:
      - "8006:8000"
    env_file:
      - ./hotel_notification_service/.env
    depends_on:
      - rabbitmq
volumes:
  redis_data:
    
